sudo: required
services:
  - docker

before_install:
  - docker build -t dcgator8/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dcgator8/react-test npm test

after_success:
  - docker build -t dcgator8/multi-client ./client
  - docker build -t dcgator8/multi-nginx ./nginx
  - docker build -t dcgator8/multi-server ./server
  - docker build -t dcgator8/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push dcgator8/multi-client
  - docker push dcgator8/multi-nginx
  - docker push dcgator8/multi-server
  - docker push dcgator8/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-444083008588
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"